%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-psen-scan-v2
Version:        0.1.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS psen_scan_v2 package

License:        LGPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       fmt-devel
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-rosconsole-bridge
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-roslaunch
Requires:       ros-noetic-rviz
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-xacro
BuildRequires:  fmt-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-code-coverage
BuildRequires:  ros-noetic-pilz-testutils
BuildRequires:  ros-noetic-rosbag
BuildRequires:  ros-noetic-rosconsole-bridge
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-rosunit
BuildRequires:  ros-noetic-sensor-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
ROS support for the Pilz laser scanner

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Mar 22 2021 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.1.6-1
- Autogenerated by Bloom

* Wed Mar 10 2021 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.1.5-1
- Autogenerated by Bloom

* Wed Jan 13 2021 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.1.4-2
- Autogenerated by Bloom

* Wed Jan 13 2021 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.1.4-1
- Autogenerated by Bloom

* Wed Dec 09 2020 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.1.3-1
- Autogenerated by Bloom

